language: python
python:
  - "2.7"
  
# command to install dependencies
install:
  - pip install myhdl 

# command to run tests
script: 
  - nosetests
  - pwd
  - echo $PYTHONPATH
  - ./scripts/run_all_examples.sh

notifications:
  email: false
