sudo: false

language: python
python:
  - "2.7"
  
addons:
  apt:
    packages:
    - iverilog

# command to install dependencies
install:
  - pip install myhdl 
  - ./scripts/make_vpi.sh
  
# command to run tests
script: 
  - nosetests -v
  - ./scripts/run_all_examples.sh

notifications:
  email: false
